version: '3'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    env_file: 
      - .env
  mongodb:
    image: mongo:latest
    ports:
        - "27017:27017"
    volumes:
        - "./data/mongo/data:/data/db"