version: '3'
services:
  api:
    build: .
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
  mongodb:
    image: mongo:latest
    ports:
        - "27017:27017"
    volumes:
        - "./data/mongo/data:/data/db"